#!/usr/bin/env node
// Compile the Tailwind classes used by the `ft web` dashboard into
// src/web-styles.ts so the dashboard works offline without the Tailwind
// play CDN. Re-run (`npm run build:web-css`) after changing classes in src/web.ts.

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const tmp = mkdtempSync(path.join(tmpdir(), 'ft-web-css-'));

try {
  const input = path.join(tmp, 'input.css');
  const output = path.join(tmp, 'output.css');
  writeFileSync(input, '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n');

  execFileSync(
    path.join(root, 'node_modules', '.bin', 'tailwindcss'),
    ['--config', path.join(root, 'tailwind.web.config.cjs'), '--input', input, '--output', output, '--minify'],
    { cwd: root, stdio: ['ignore', 'ignore', 'inherit'] },
  );

  const css = readFileSync(output, 'utf-8');
  writeFileSync(
    path.join(root, 'src', 'web-styles.ts'),
    '// Generated by scripts/build-web-css.mjs — do not edit by hand.\n' +
    `export const WEB_CSS = ${JSON.stringify(css)};\n`,
  );
  console.log(`Wrote src/web-styles.ts (${css.length} bytes of CSS)`);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
